/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { OrderStatusEnum, StoreController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('StoreController', () => {
  let controller : StoreController;

  beforeAll(() => {
    controller = new StoreController(testClient);
  });

  it('should Test getInventory', async () => {
    const response = await makeApiCall(
      () => controller.getInventory()
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test placeOrder', async () => {
    const id = BigInt(10);

    const petId = BigInt(198772);

    const quantity = 7;

    const shipDate = '2023-05-31T00:00:00Z';

    const orderStatus = OrderStatusEnum.Approved;

    const complete = true;

    const response = await makeApiCall(
      () => controller.placeOrder(
        id,
        petId,
        quantity,
        shipDate,
        orderStatus,
        complete
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
