/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment } from '../src';

export const testClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.SWAGGER_PETSTORE_OPEN_API_3_0_LIB_ENVIRONMENT;
  const timeout = process.env.SWAGGER_PETSTORE_OPEN_API_3_0_LIB_TIMEOUT;
  const apiKey = process.env.SWAGGER_PETSTORE_OPEN_API_3_0_LIB_API_KEY;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (apiKey !== undefined) {
    config.customHeaderAuthenticationCredentials = { api_key: apiKey };
  }

  return config;
}
