/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { UserController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('UserController', () => {
  let controller : UserController;

  beforeAll(() => {
    controller = new UserController(testClient);
  });

  it('should Test createUsersWithListInput', async () => {
    const response = await makeApiCall(
      () => controller.createUsersWithListInput(undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test loginUser', async () => {
    const response = await makeApiCall(
      () => controller.loginUser(undefined, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'X-Rate-Limit': ['', false],
      'X-Expires-After': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
