/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Address, addressSchema } from './address';

export interface Customer {
  id?: bigint;
  username?: string;
  address?: Address[];
}

export const customerSchema: Schema<Customer> = object({
  id: ['id', optional(bigint())],
  username: ['username', optional(string())],
  address: ['address', optional(array(lazy(() => addressSchema)))],
});
