/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderStatusEnum
 */
export enum OrderStatusEnum {
  Placed = 'placed',
  Approved = 'approved',
  Delivered = 'delivered',
}

/**
 * Schema for OrderStatusEnum
 */
export const orderStatusEnumSchema: Schema<OrderStatusEnum> = stringEnum(
  OrderStatusEnum
);
