/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Category, categorySchema } from './category';
import { PetStatusEnum, petStatusEnumSchema } from './petStatusEnum';
import { Tag, tagSchema } from './tag';

export interface Pet {
  name: string;
  photoUrls: string[];
  id?: bigint;
  category?: Category;
  tags?: Tag[];
  /** pet status in the store */
  petStatus?: PetStatusEnum;
}

export const petSchema: Schema<Pet> = object({
  name: ['name', string()],
  photoUrls: ['photoUrls', array(string())],
  id: ['id', optional(bigint())],
  category: ['category', optional(lazy(() => categorySchema))],
  tags: ['tags', optional(array(lazy(() => tagSchema)))],
  petStatus: ['petStatus', optional(petStatusEnumSchema)],
});
