/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PetStatusEnum
 */
export enum PetStatusEnum {
  Available = 'available',
  Pending = 'pending',
  Sold = 'sold',
}

/**
 * Schema for PetStatusEnum
 */
export const petStatusEnumSchema: Schema<PetStatusEnum> = stringEnum(
  PetStatusEnum
);
