/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

export interface Tag {
  id?: bigint;
  name?: string;
}

export const tagSchema: Schema<Tag> = object({
  id: ['id', optional(bigint())],
  name: ['name', optional(string())],
});
