/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, number, object, optional, Schema, string } from '../schema';

export interface User {
  id?: bigint;
  username?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  phone?: string;
  /** User Status */
  userStatus?: number;
}

export const userSchema: Schema<User> = object({
  id: ['id', optional(bigint())],
  username: ['username', optional(string())],
  firstName: ['firstName', optional(string())],
  lastName: ['lastName', optional(string())],
  email: ['email', optional(string())],
  password: ['password', optional(string())],
  phone: ['phone', optional(string())],
  userStatus: ['userStatus', optional(number())],
});
